updated with PhD info

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -4,11 +4,10 @@
 
 # Parse cmd arguments
 
-SRC_BRANCH="master"
+SRC_BRANCH="main"
 DEPLOY_BRANCH="gh-pages"
-CI_MODE=false
 
-USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push] [--ci]"
+USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push]"
 
 while [[ $# > 0 ]]; do
     key="$1"
@@ -19,8 +18,6 @@ while [[ $# > 0 ]]; do
         exit 0
         ;;
         -u|--user)
-        SRC_BRANCH="source"
-        DEPLOY_BRANCH="master"
         ;;
         -s|--src)
         SRC_BRANCH="$2"
@@ -35,9 +32,6 @@ while [[ $# > 0 ]]; do
         ;;
         --no-push)
         NO_PUSH="--no-push"
-        ;;
-        --ci)
-        CI_MODE=true
         ;;
         *)
         echo "Option $1 is unknown." >&2
@@ -55,15 +49,11 @@ echo "Deploying..."
 echo "Source branch: $SRC_BRANCH"
 echo "Deploy branch: $DEPLOY_BRANCH"
 
-# Skip confirmation prompt in CI mode
-if [[ "$CI_MODE" == "false" ]]; then
-    read -r -p "Do you want to proceed? [y/N] " response
-    if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]; then
-        echo "Aborting."
-        [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
-    fi
-else
-    echo "CI mode detected, skipping confirmation prompt."
+read -r -p "Do you want to proceed? [y/N] " response
+if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
+then
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
 # Check if there are any uncommitted changes
@@ -104,6 +94,9 @@ export JEKYLL_ENV=production
 
 # Build site
 bundle exec jekyll build
+
+# Purge unused css
+purgecss -c purgecss.config.js
 
 # Delete and move files
 find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name 'CNAME' ! -name '.gitignore' -exec rm -rf {} \;
